version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test_pass
    ports:
      - 27017:27017

  server:
    build: ./server
    restart: always
    environment:
      MONGO_USERNAME: root
      MONGO_PORT: 27017
      MONGO_PASSWORD: test_pass
      SERVER_PORT: 8082
    network_mode: "host"
    depends_on:
      - mongo

  datagen:
    build: ./data_generator
    restart: always
    environment:
      MONGO_USERNAME: root
      MONGO_PORT: 27017
      MONGO_PASSWORD: test_pass
    network_mode: "host"
    depends_on:
      - mongo
